<a href="https://colab.research.google.com/github/alscop/ESAA-26-1/blob/main/0410_%EC%84%B8%EC%85%98_%ED%8C%8C%EC%9D%B4%ED%86%A0%EC%B9%98_%EC%97%B0%EC%8A%B5%EB%AC%B8%EC%A0%9C_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch

# Create random tensor
random_tensor = torch.rand(size=(7, 7))

In [2]:
print(random_tensor)

tensor([[0.6508, 0.8661, 0.9274, 0.1890, 0.8818, 0.8947, 0.4488],
        [0.0984, 0.7128, 0.0365, 0.0302, 0.9935, 0.1266, 0.0509],
        [0.2762, 0.4948, 0.8213, 0.6446, 0.1746, 0.0677, 0.2381],
        [0.6909, 0.9102, 0.0200, 0.7424, 0.7089, 0.2130, 0.9137],
        [0.1532, 0.0102, 0.8939, 0.0722, 0.4414, 0.9497, 0.7215],
        [0.6796, 0.4435, 0.9507, 0.1160, 0.5447, 0.4529, 0.9509],
        [0.2615, 0.0560, 0.7824, 0.9828, 0.4186, 0.4553, 0.5138]])


In [4]:
random_tensor.shape

torch.Size([7, 7])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [6]:
# Create another random tensor
tensor_B = torch.rand(size=(1,7))

# Perform matrix multiplication
matrix_multiplication = torch.matmul(random_tensor, tensor_B.T)

In [7]:
matrix_multiplication

tensor([[2.9276],
        [0.8519],
        [1.5939],
        [2.4388],
        [2.3214],
        [2.8416],
        [2.2501]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [10]:
# Set manual seed
random_seed = 0
torch.manual_seed(random_seed)

# Create two random tensors
tensor_A = torch.rand(7, 7)

torch.manual_seed(random_seed)
tensor_B = torch.rand(1, 7)

# Matrix multiply tensors
output = torch.matmul(tensor_A, tensor_B.T)

print(output, output.shape)

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]]) torch.Size([7, 1])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [11]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [13]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
tensor_A = torch.rand(size=(2, 3)).to(device)
tensor_B = torch.rand(size=(2, 3)).to(device)

print(tensor_A)
print(tensor_B)

Device: cuda
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [14]:
# Perform matmul on tensor_A and tensor_B
output = torch.matmul(tensor_A, tensor_B.T)

In [15]:
print(output, output.shape)

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0') torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [17]:
# Find max
print('max: ', output.max())

# Find min
print('min: ', output.min())

max:  tensor(0.5617, device='cuda:0')
min:  tensor(0.3647, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [18]:
# Find arg max
print('arg max: ', output.argmax())

# Find arg min
print('arg min: ', output.argmin())

arg max:  tensor(3, device='cuda:0')
arg min:  tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [19]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_A = torch.rand(size=(1, 1, 1, 10))

# Remove single dimensions
tensor_B = tensor_A.squeeze()

# Print out tensors and their shapes
print(tensor_A, tensor_A.shape)
print(tensor_B, tensor_B.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
