<a href="https://colab.research.google.com/github/alscop/ESAA-26-1/blob/main/ESAA_OB_week05_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

> <딥러닝 파이토치 교과서> 1장-2장 p.18-60

# 1장. 머신러닝과 딥러닝

## 1.1 인공지능, 머신러닝과 딥러닝

인공지능 > 머신러닝> 딥러닝

- 머신러닝: 데이터를 인간이 먼저 전처리. 데이터 인식, 학습, 해결
- 딥러닝: 전처리 과정 생략, 데이터 스스로 분석, 답 도출

## 1.2 머신 러닝이란

컴퓨터가 학습할 수 있게 하는 알고리즘과 기술을 개발

### 1.2.1 머신 러닝 학습 과정

- 학습 단계
- 예측 단계

주요 구성 요소  
- 데이터(훈련 데이터셋(+ 검증데이터셋), 테스트 데이터셋)
- 모델: 최종 결과물(가설)

### 1.2.2 머신 러닝 학습 알고리즘

- 지도 학습: 정답 알려주고 학습시킴
- 비지도 학습: 정답 안 알려주고, 비슷한 데이터 클러스터링
- 강화 학습: 매우 복잡. 행동에 대한 보상 받으며 학습 진행

## 1.3 딥러닝이란

인간의 신경망 원리를 모방한 심층 신경망 이론을 기반으로 고안된 머신 러닝 방법의 일종

### 1.3.1 딥러닝 학습 과정

- 데이터 준비
- 모델(모형) 정의  
: 신경망 생성. 은닉충 개수에 따라 성능 향상 BUT 과적합 주의.
- 모델(모형) 컴파일  
: 활성화함수, 손실함수, 옵티마이저 선택 - 데이터셋 형태에 따라 사용, 과적합 주의
- 모델(모형) 훈련  
: 한 번에 처리할 데이터양 지정(학습 속도, 메모리 문제 관련), **'에포크'**, 값 변화 시각적으로 확인하며 파라미터와 하이퍼파라미터 최적값 도출
- 모델(모형) 예측  
: 실제 예측 진행, 예측력 낮으면 튜닝&재설계

핵심 구성 요소
- 신경망
- 역전파(가중치 값 업데이트)

### 1.3.2 딥러닝 학습 알고리즘

- 지도 학습
  - 합성곱 신경망: 이미지 분류/인식/분할  
  - 순환 신경망: 시계열 데이터 분류, BUT 기울기 소멸 문제 존재  
  - LSTM: 순환 신경망 + gate 3개(망각/입력/출력 게이트), 기울기 소멸 문제 해결  
- 비지도 학습
  - 워드 임베딩: 자연어 처리 시 단어를 벡터로 표현시킴
    - 워드투벡터(Word2Vec)
    - 글로브(GloVe)
  - 군집: 아무 정보 없는 상태에서 데이터 분류(머신러닝 학습 향상에 기여)  
- 전이 학습: 사전 학습 모델을 가지고 원하는 학습에 미세 조정 기법을 이용해 학습시키는 방법.  
- 사전 학습 모델: 풀고자 하는 문제와 비슷하면서 많은 데이터로 이미 학습이 되어 있는 모델
  - VGG
  - 인셉션(Inception)
  - MobileNet
- 강화 학습: 머신러닝과 동일





# 2장. 실습 환경 설정과 파이토치 기초

## 2.1 파이토치 개요

Torch: 과학 연산을 위한 라이브러리로 공개(NumPy처럼) ->  답러닝 프레임워크로 발전

사용 대상
- 넘파이를 대체하면서 GPU를 이용한 연산이 필요한 경우
- 최대한의 유연성과 속도를 제공하는 딥러닝 연구 플랫폼이 필요한 경우

### 2.1.1 파이토치 특징 및 장점

[특징]  
GPU에서 텐서 조작 및 동적 신경망 구축이 가능한 프레임워크

- GPU: 연산 속도를 빠르게 하는 역할. 미분, 병렬 연산에 GOOD
- **텐서(Tensor)**: 파이토치의 데이터 형태, 단일 데이터 형식으로 된 자료들의 다차원 행렬
- 동적 신경망: 훈련을 반복할 때마다 네트워크 변경이 가능한 신경망
  - 학습 중 은닉층 추가/제거 등 모델 네트워크 조작 가능
  - 연산 그래프와 연산 분리해 생각할 필요 X, 코드 이해 쉬움


[장점]  
- 효율적 계산(단순함)
- 낮은 CPU 활용(성능)
- 직관적인 인터페이스, 낮은 진입장벽

### 2.1.2 파이토치의 아키텍쳐

세 개의 계층으로 나누어 설명 가능  
1. 파이토치 API(상위)  
- 사용자가 사용하는 라이브러리
2. 파이토치 엔진(중간)
- 다차원 텐서 및 자동 미분 처리
3. 연산 처리(하위)
- 실질적 계산 위한 라이브러리 위치(C, CUDA 등)


#### 파이토치 API

- 사용자가 이해하기 쉬운 API를 제공하여 텐서에 대한 처리와 신경망을 구축하고 훈련할 수 있도록함.  
- 실제 계산 수행 X  
- 작업 전달만  

제공 패키지
- torch: GPU 지원하는 텐서 패키지
- torch.autograd: 자동 미분 패키지
- torch.nn: 신경망 구축 및 훈련 패키지
- torch.multiprocessing: 파이썬 멀티 프로세싱 패키지
- torch.utils: DataLoader 및 기타 유틸리티를 제공하는 패키지  


#### 파이토치 엔진  

Autograd C++, Aten C++, JIT C++, Python API로 구성됨.

- Autograd C++: 미분 자동 계산
- Aten C++: 텐서 라이브러리 제공
- JIT C++: 계산 최적화하기 위한 JIT 컴파일러
- Python API: 파이토치 엔진 라이브러리가 Python API 형태로 제공됨


#### 연산 처리

C 또는 CUDA 패키지, 상위의 API에서 할당된 거의 모든 계산을 수행  
CPU, GPU((Torch, Torch CUDA) 이용






## 2.2 파이토치 기초 문법

텐서 !!! 제일 중요.

### 2.2.1 텐서 다루기

#### 텐서 생성 및 변환

NumPy의 ndarray랑 비슷.  

> 텐서 생성

In [13]:
import torch
print(torch.tensor([[1,2], [3,4]])) # 2차원 형태의 텐서 생성
print(torch.tensor([[1,2], [3,4]], device='cuda:0')) # GPU에 텐서 생성
print(torch.tensor([[1,2], [3,4]], dtype=torch.float64)) # dtype을 이용하여 텐서 생성

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]], device='cuda:0')
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


> 텐서를 ndarray로 변환

In [14]:
temp = torch.tensor([[1,2], [3,4]])
print(temp.numpy()) # 텐서를 ndarray로 변환

temp = torch.tensor([[1,2], [3,4]], device='cuda:0')
print(temp.to("cpu").numpy()) # GPU상의 텐서를 CPU의 텐서로 변환한 후 ndarray로 변환

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


#### 텐서의 인덱스 조작

배열처럼 인덱스 바로 지정/슬라이스 등 사용 가능

자료형
- torch.FloatTensor: 32비트의 부동 소수점
- torch.DoubleTensor: 64비트의 부동 소수점
- torch.LongTensor: 64비트의 부호가 있는 정수  
... 등등

> 텐서 인덱스 조작


In [15]:
temp = torch.FloatTensor([1,2,3,4,5,6,7]) # 파이토치로 1차원 벡터 생성
print(temp[0], temp[1], temp[-1]) # 인덱스로 접근
print('------------------------')
print(temp[2:5], temp[4:-1]) # 슬라이스로 접근

tensor(1.) tensor(2.) tensor(7.)
------------------------
tensor([3., 4., 5.]) tensor([5., 6.])


-1 인덱스 = 맨 뒤에서 시작  

#### 텐서 연산 및 차원 조작

- 텐서 간 타입이 같아야 연산 가능  

> 사칙연산

In [16]:
# 길이가 3인 벡터 생성
v = torch.tensor([1,2,3])
w = torch.tensor([3,4,6])

# 길이가 같은 벡터 간 뺄셈 연산
print(w - v)

tensor([2, 2, 3])


> 차원 조작

- `view` 이용
- 텐서 결합: `stack`, `cat`(다른 길이 텐서를 하나로 병합)
- 차원 교환: `t`, `transpose`(전치, 차원 순서 변경)

In [17]:
# 2X2 행렬 생성
temp = torch.tensor([
    [1,2], [3,4]])

print(temp.shape)
print('-----------------------')
print(temp.view(4,1)) # 2X2 행렬을 4X1로 변형
print('-----------------------')
print(temp.view(-1)) # 2X2 행렬을 1차원 벡터로 변형
print('-----------------------')
print(temp.view(1, -1)) # -1은 (1,?)와 같은 의미, 다른 차원으로부터 해당 값 유추하겠다는 뜻
print('-----------------------')
print(temp.view(-1, 1)) # 마찬가지로 (?, 1)이 됨

torch.Size([2, 2])
-----------------------
tensor([[1],
        [2],
        [3],
        [4]])
-----------------------
tensor([1, 2, 3, 4])
-----------------------
tensor([[1, 2, 3, 4]])
-----------------------
tensor([[1],
        [2],
        [3],
        [4]])


### 2.2.2 데이터 준비

- Python Pandas 이용
- 파이토치에서 제공하는 데이터 이용

#### 단순하게 파일을 불러와서 사용



In [18]:
!pip install pandas

In [19]:
import pandas as pd
import torch
# data = pd .read_csv(' .. /class2.csv ’ )

In [20]:
# CSV 파일의 칼럼 값을 넘파이 배열로 받고 Tensor(dtype)으로 바꿔줌
# x = torch.from_numpy(data['x'].values).unsqueeze(dim=1).float()
# y = torch .from_numpy(data['y'].values).unsqueeze(dim=1).float()

### 커스텀 데이터셋을 만들어서 사용

데이터 한 번에 메모리에 불러오면 시간/비용 측면에서 비효율적.  
-> 조금씩 나누어 불러서 사용하는 방식이 커스텀 데이터셋!

In [21]:
'''
class CustomDataset(torch.utils.data.Dataset):
def __init__(self): # 필요한 변수를 선언하고，데이터셋의 전처리를 해 주는 함수
def __len__(self): # 데이터셋의 길이. 즉 층 샘플의 수를 가져오는 함수
def __getitem__(self,index): # 데이터셋에서 특정 데이터를 가져오는 함수
'''

'\nclass CustomDataset(torch.utils.data.Dataset): \ndef __init__(self): # 필요한 변수를 선언하고，데이터셋의 전처리를 해 주는 함수 \ndef __len__(self): # 데이터셋의 길이. 즉 층 샘플의 수를 가져오는 함수 \ndef __getitem__(self,index): # 데이터셋에서 특정 데이터를 가져오는 함수\n'

In [22]:
import pandas as pd
import torch
from torch .utils.data import Dataset
from torch.utils.data import DataLoader

'''
class CustomDataset (Dataset):
  def __init__ (self, csv_file): # csv_file 파라미터를 통해 데이터셋을 불러옵니다.
    self.label = pd.read_csv(csv_file)

  def __len__ (self): # 전체 데이터셋의 크기(size)를 반환.
    return len(self.label)

  def __getitem__ (self, idx): # 전체 x와 y 데이터 중에 해당 idx번째의 데이터를 가져옵니다.
    sample = torch.tensor(self.label.iloc[idx,0:3]).int()
    label = torch.tensor(self.label.iloc[idx,3]).int()
    return sample, label

tensor_dataset = CustomDataset('.. /covtype.csv') # 데이터셋으로 covtype.csv를 사용합니다.
dataset = DataLoader(tensor_dataset, batch_size=4, shuffle=True )
'''

"\nclass CustomDataset (Dataset): \n  def __init__ (self, csv_file): # csv_file 파라미터를 통해 데이터셋을 불러옵니다. \n    self.label = pd.read_csv(csv_file)\n\n  def __len__ (self): # 전체 데이터셋의 크기(size)를 반환.\n    return len(self.label) \n  \n  def __getitem__ (self, idx): # 전체 x와 y 데이터 중에 해당 idx번째의 데이터를 가져옵니다. \n    sample = torch.tensor(self.label.iloc[idx,0:3]).int() \n    label = torch.tensor(self.label.iloc[idx,3]).int() \n    return sample, label \n\ntensor_dataset = CustomDataset('.. /covtype.csv') # 데이터셋으로 covtype.csv를 사용합니다. \ndataset = DataLoader(tensor_dataset, batch_size=4, shuffle=True ) \n"

#### 파이토치에서 제공하는 데이터셋 사용

토치비전  


In [23]:
!pip install requests

### 2.2.3 모델 정의

모델을 정의하기 위해서는 모듈(module)을 상속한 클래스를 사용.

- 계층(layer): 모듈 또는 모듈을 구성하는 한 개의 계층. 합성곱층, 선형계층 등
- 모듈(module): 한 개 이상의 계층이 모여서 구성된 것. 모듈이 모여 새로운 모듈을 만들수도 있음.
- 모델(model): 최종적으로 원하는 네트워크. 한 개의 모듈이 모델이 될 수도 있음

#### 단순 신경망을 정의하는 방법

nn.Module을 상속받지 않는 매우 단순한 모델 만들때 사용.  
구현 쉽고 단순

In [24]:
# model = nn.Linear(in_features=1, out_features=1, bias=True)

#### nn.Module()을 상속하여 정의하는 방법

- `__init__()`: 모델에서 사용될 모듈, 활성화 함수 등 정의
- `forward()`: 모델에서 실행되어야하는 연산 정의


In [26]:
'''
class MLP(Module):
  def __init__ (self, inputs):
    super(MLP, self).__init__()
    self.layer = Linear(inputs,1) # 계층 정의
    self.activation = Sigmoid() # 활성화 함수 정의

  def forward (self, X):
    X = self.layer(X)
    X = self.activation(X)
    return X
'''

'\nclass MLP(Module):\n  def __init__ (self, inputs):\n    super(MLP, self).__init__()\n    self.layer = Linear(inputs,1) # 계층 정의\n    self.activation = Sigmoid() # 활성화 함수 정의\n\n  def forward (self, X):\n    X = self.layer(X)\n    X = self.activation(X) \n    return X \n'

#### Sequential 신경망을 정의하는 방법

`nn.Sequential`: __init__()에서 사용할 네트워크 모델 정의, forward( ) 함수에서는 모델에서 실행되어야 할 계산을 좀 더 가독성이 뛰어난 코드로 작성 가능



In [27]:
import torch.nn as nn
class MLP(nn.Module):
  def __init__(self):
    super(MLP, self).__init__()
    self.layer1 = nn.Sequential(
        nn.Conv2d(in_channels=3, out_channels=64, kernel_size=5),
        nn.ReLU(inplace=True),
        nn.MaxPool2d(2))

    self.layer2 = nn.Sequential(
        nn.Conv2d(in_channels=64, out_channels=30, kernel_size=5),
        nn.ReLU(inplace=True),
        nn.MaxPool2d(2))

    self.layer3 = nn.Sequential(
        nn.Linear(in_features=30*5*5, out_features=10, bias=True),
        nn.ReLU(inplace=True))

    def forward(self, x):
      x = self.layer1(x)
      x = self.layer2(x)
      x = x.view(x.shape[0], -1)
      x = self.layer3(x)
      return x

# 모델에 대한 객체 생성
model = MLP()

print("Printing children\n---------------------")
print(list(model.children()))
print('\n\nPrinting Modules\n----------------------')
print(list(model.modules()))

Printing children
---------------------
[Sequential(
  (0): Conv2d(3, 64, kernel_size=(5, 5), stride=(1, 1))
  (1): ReLU(inplace=True)
  (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
), Sequential(
  (0): Conv2d(64, 30, kernel_size=(5, 5), stride=(1, 1))
  (1): ReLU(inplace=True)
  (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
), Sequential(
  (0): Linear(in_features=750, out_features=10, bias=True)
  (1): ReLU(inplace=True)
)]


Printing Modules
----------------------
[MLP(
  (layer1): Sequential(
    (0): Conv2d(3, 64, kernel_size=(5, 5), stride=(1, 1))
    (1): ReLU(inplace=True)
    (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer2): Sequential(
    (0): Conv2d(64, 30, kernel_size=(5, 5), stride=(1, 1))
    (1): ReLU(inplace=True)
    (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer3): Sequential(
    (0): Linear(in_features=750

nn.Sequential은 모델 계층이 복잡할수록 효과 뛰어남

#### 함수로 신경망을 정의하는 방법

- Sequential을 이용하는 것과 동일
- 함수로 선언할 경우 변수에 저장해 놓은 계층들을 재사용 가능
- 모델 복잡해짐 -> 이 경우, 함수보다 nn.Module() 상속받아 사용하는걸 추천.


In [28]:
def MLP(in_features=1, hidden_features=20, out_features=1):
  hidden = nn.Linear(in_features=in_features, out_features=hidden_features,
                     bias=True)
  activation = nn.ReLU()
  output = nn.Linear(in_features=hidden_features, out_features=out_features, bias=True)
  net = nn.Sequential(hidden, activation, output)
  return net

### 2.2.4 모델의 파라미터 정의

- 손실 함수: 학습하는 동안 출력과 실제 값(정답) 사이의 오차를 측정(정확성 측정)
- 옵티마이저: 데이터와 손실 함수를 바탕으로 모델의 업데이트 방법을 결정
- 학습률 스케쥴러:  미리 지정한 횟수의 에포크를 지날 때마다 학습률을 감소시켜줌
- 지표: 훈련과 테스트 단계를 모니터링



In [29]:
# 예시 생략

#### 2.2.5 모델 훈련

모델 학습 = " y=wx+b 라는 함수에서 w, b의 적절한 값 찾기 "  

- `optimizer.zero_grad()` 메서드 이용, 기울기 초기화  
- `loss.backward()` 메서드 이용, 새 기울기 값이 이전 기울기 값에 **누적**해 계산됨: 누적 계산 필요없는 모델에서는 불필요하므로 계속 위 함수 이용해 초기화  




In [30]:
# 예시 생략

#### 2.2.6 모델 평가

테스트 데이터셋으로 평가.
1. 함수 이용

2. 모듈 이용



In [31]:
!pip install torchmetrics

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 983.4/983.4 kB 26.4 MB/s eta 0:00:00


> 함수 이용해 모델 평가하는 코드

In [32]:
import torch
import torchmetrics

preds = torch.randn(10, 5).softmax(dim=-1)
target = torch.randint(5, (10,))

acc = torchmetrics.functional.accuracy(preds, target, task='multiclass', num_classes=5)

> 모듈 이용해 모델 평가하는 코드

In [33]:
# 모델 평가(정확도) 초기화
metric = torchmetrics.Accuracy(task='multiclass', num_classes=5)

n_batches = 10
for i in range(n_batches):
  preds = torch.randn(10, 5).softmax(dim=-1)
  target = torch.randint(5, (10,))

  acc = metric(preds, target)
  # 현재 배치에서 모델 평가(정확도)
  print(f'Accuracy on batch {i}: {acc}')

acc = metric.compute()
# 모든 배치에서 모델 평가(정확도)
print(f'Accuracy on all data: {acc}')

Accuracy on batch 0: 0.20000000298023224
Accuracy on batch 1: 0.30000001192092896
Accuracy on batch 2: 0.20000000298023224
Accuracy on batch 3: 0.30000001192092896
Accuracy on batch 4: 0.10000000149011612
Accuracy on batch 5: 0.20000000298023224
Accuracy on batch 6: 0.0
Accuracy on batch 7: 0.20000000298023224
Accuracy on batch 8: 0.4000000059604645
Accuracy on batch 9: 0.5
Accuracy on all data: 0.23999999463558197


+ 사이킷런에서 제공하는 혼동 행렬 이용하는 방법도 고려 가능!

### 2.2.7 훈련 과정 모니터링

학습이 진행되는 과정에서 각 파라미터 어떤 값이 어떻게 변화하는지 모니터링 어려움.

-> **텐서보드** 사용하면 시각화 & 성능 추적, 평가 용이!!

1. 텐서보드 설정
2. 텐서보드에 기록
3. 텐서보드를 사용해 모델 구조 관찰

In [34]:
# 코드 생략